from __future__ import annotations
from typing import Tuple, List
import sys
import types

if 'pkg_resources' not in sys.modules:
    _fake = types.ModuleType('pkg_resources')
    _fake.get_distribution = lambda name: type('D', (), {'version': '0.0.0'})()
    _fake.DistributionNotFound = Exception
    _fake.RequirementParseError = Exception
    sys.modules['pkg_resources'] = _fake

from crewai import Agent, Task, Crew, Process, LLM

from config import (
    get_openai_key, get_anthropic_key,
    get_openai_model, get_anthropic_model_default,
    OPENAI_TEMPERATURE, MIN_BULLETS, MAX_BULLETS, MAX_BULLET_CHARS,
    ANTHROPIC_MAX_TOKENS
)
from utils.schema import safe_load_json, validate_bullets_payload, SchemaError
from utils.bullets import normalize_bullets


def run_resume_crew(
    subject: str,
    description: str,
    github_url: str,
    resume_text: str,
    claude_model: str,
) -> Tuple[List[str], List[str], List[str], str]:

    openai_llm = LLM(
        model=f"openai/{get_openai_model()}",
        api_key=get_openai_key(),
        temperature=OPENAI_TEMPERATURE,
    )

    claude_llm = LLM(
        model=f"anthropic/{claude_model}",
        api_key=get_anthropic_key(),
        temperature=0.3,
        max_tokens=ANTHROPIC_MAX_TOKENS,
    )

    bullet_writer = Agent(
        role="Resume Bullet Point Writer",
        goal="Generate 2-3 concise, high-impact resume bullet points for a given project",
        backstory=(
            "You are an expert resume writer specializing in technical roles at top tech companies. "
            "You write action-verb led, specific, and quantified bullet points. "
            "You never invent metrics and always return valid JSON."
        ),
        llm=openai_llm,
        verbose=True,
        allow_delegation=False,
    )

    resume_critic = Agent(
        role="Senior Technical Recruiter",
        goal="Evaluate a full resume and provide structured, actionable feedback",
        backstory=(
            "You are a senior recruiter at top tech companies with 10+ years of experience. "
            "You give specific, honest feedback on resume clarity, impact, and role fit. "
            "You review the bullet points generated by the Bullet Writer as part of the updated resume."
        ),
        llm=claude_llm,
        verbose=True,
        allow_delegation=False,
    )

    github_line = f"GitHub (optional): {github_url}" if github_url else ""

    bullet_task = Task(
        description=f"""
Generate 2-3 concise, high-impact resume bullet points for the following project.

Rules:
- Return ONLY valid JSON (no markdown, no extra text).
- Bullets must be 1 line each, action-verb led, and specific.
- Do NOT invent metrics. If a metric is missing, put it under "missing_info_questions".
- If you must make an assumption, put it under "assumptions" (do not put it in bullets).

Return this exact JSON schema:
{{
  "bullets": ["...","..."],
  "assumptions": [],
  "missing_info_questions": []
}}

Project Title: {subject}
Project Description: {description}
{github_line}
""".strip(),
        expected_output='Valid JSON with keys: bullets (list), assumptions (list), missing_info_questions (list)',
        agent=bullet_writer,
    )

    critique_task = Task(
        description=f"""
You are reviewing a resume after the Bullet Writer has updated the first project section.

Here is the full updated resume text:
{resume_text}

The Bullet Writer just generated new bullets for the first project (their output is in context).
Take those bullets into account in your evaluation.

Give:
1. 3-5 specific improvement suggestions
2. Weak or vague bullet points, if any
3. Suggestions for tailoring to roles like: data analyst, product manager, ML engineer

Return your response in a clear, structured format.
""".strip(),
        expected_output='Structured feedback with improvement suggestions, weak bullets, and role-tailoring advice',
        agent=resume_critic,
        context=[bullet_task],
    )

    crew = Crew(
        agents=[bullet_writer, resume_critic],
        tasks=[bullet_task, critique_task],
        process=Process.sequential,
        verbose=True,
    )

    result = crew.kickoff()

    # Parse bullet task output
    bullet_raw = result.tasks_output[0].raw if result.tasks_output else ""
    try:
        payload = safe_load_json(bullet_raw)
        bullets, assumptions, missing = validate_bullets_payload(
            payload, min_bullets=MIN_BULLETS, max_bullets=MAX_BULLETS
        )
        bullets = normalize_bullets(bullets, max_chars=MAX_BULLET_CHARS, max_bullets=MAX_BULLETS)
    except SchemaError:
        fallback = normalize_bullets(
            [ln.strip("• ").strip() for ln in bullet_raw.splitlines() if ln.strip()],
            max_chars=MAX_BULLET_CHARS
        )
        fallback = fallback[:MAX_BULLETS]
        if len(fallback) < MIN_BULLETS:
            fallback = [
                "Built an end-to-end resume editing workflow emphasizing reliability and structured LLM output.",
                "Implemented multi-agent pipeline with schema validation to reduce hallucinations and formatting errors.",
            ][:MAX_BULLETS]
        bullets, assumptions, missing = fallback, [], []

    feedback = result.tasks_output[1].raw if len(result.tasks_output) > 1 else ""

    return bullets, assumptions, missing, feedback
