from __future__ import annotations
from typing import Tuple, List

from openai import OpenAI
import anthropic

from config import (
    get_openai_key, get_anthropic_key,
    get_openai_model, get_anthropic_model_default,
    OPENAI_TEMPERATURE, MIN_BULLETS, MAX_BULLETS, MAX_BULLET_CHARS,
    ANTHROPIC_MAX_TOKENS
)
from utils.schema import safe_load_json, validate_bullets_payload, SchemaError
from utils.bullets import normalize_bullets


class Agent:
    """Base agent class — defines role, goal, backstory, and LLM."""
    def __init__(self, role: str, goal: str, backstory: str, llm: str):
        self.role = role
        self.goal = goal
        self.backstory = backstory
        self.llm = llm


class Task:
    """Defines what an agent should do and what output to expect."""
    def __init__(self, description: str, expected_output: str, agent: Agent, context: list = None):
        self.description = description
        self.expected_output = expected_output
        self.agent = agent
        self.context = context or []


class Crew:
    """
    Orchestrates agents and tasks sequentially.
    Each task can receive output from previous tasks as context.
    """
    def __init__(self, tasks: list, claude_model: str = None):
        self.tasks = tasks
        self.task_outputs = []
        self.claude_model = claude_model or get_anthropic_model_default()

    def kickoff(self) -> list:
        self.task_outputs = []
        for task in self.tasks:
            context_str = ""
            if task.context:
                context_str = "\n\n".join(
                    f"Output from previous agent ({t.agent.role}):\n{out}"
                    for t, out in zip(task.context, self.task_outputs[-len(task.context):])
                )
            output = self._run_task(task, context_str)
            self.task_outputs.append(output)
        return self.task_outputs

    def _run_task(self, task: Task, context_str: str) -> str:
        full_prompt = task.description
        if context_str:
            full_prompt = f"{context_str}\n\n{task.description}"

        if task.agent.llm == "openai":
            client = OpenAI(api_key=get_openai_key())
            resp = client.chat.completions.create(
                model=get_openai_model(),
                messages=[
                    {"role": "system", "content": f"You are a {task.agent.role}. {task.agent.backstory}"},
                    {"role": "user", "content": full_prompt}
                ],
                temperature=OPENAI_TEMPERATURE,
            )
            return (resp.choices[0].message.content or "").strip()

        elif task.agent.llm == "anthropic":
            client = anthropic.Anthropic(api_key=get_anthropic_key())
            resp = client.messages.create(
                model=self.claude_model,
                system=f"You are a {task.agent.role}. {task.agent.backstory}",
                max_tokens=ANTHROPIC_MAX_TOKENS,
                messages=[{"role": "user", "content": full_prompt}],
            )
            return "".join(
                block.text for block in resp.content
                if getattr(block, "type", None) == "text"
            ).strip()

        return ""


def run_resume_crew(
    subject: str,
    description: str,
    github_url: str,
    resume_text: str,
    claude_model: str,
) -> Tuple[List[str], List[str], List[str], str]:

    # --- Define Agents ---
    bullet_writer = Agent(
        role="Resume Bullet Point Writer",
        goal="Generate 2-3 concise, high-impact resume bullet points for a given project",
        backstory=(
            "Expert resume writer specializing in technical roles at top tech companies. "
            "Writes action-verb led, specific, quantified bullets. Never invents metrics. "
            "Always returns valid JSON."
        ),
        llm="openai",
    )

    resume_critic = Agent(
        role="Senior Technical Recruiter",
        goal="Evaluate a full resume and provide structured, actionable feedback",
        backstory=(
            "Senior recruiter at top tech companies with 10+ years experience. "
            "Reviews updated resume including bullets generated by the Bullet Writer agent. "
            "Gives specific, honest feedback on clarity, impact, and role fit."
        ),
        llm="anthropic",
    )

    # --- Define Tasks ---
    github_line = f"GitHub: {github_url}" if github_url else ""

    bullet_task = Task(
        description=f"""
Generate 2-3 concise, high-impact resume bullet points for the following project.

Rules:
- Return ONLY valid JSON (no markdown, no extra text).
- Bullets must be 1 line each, action-verb led, and specific.
- Do NOT invent metrics. If missing, put under "missing_info_questions".
- Assumptions go under "assumptions", not in bullets.

Return this exact JSON schema:
{{
  "bullets": ["...","..."],
  "assumptions": [],
  "missing_info_questions": []
}}

Project Title: {subject}
Project Description: {description}
{github_line}
""".strip(),
        expected_output="Valid JSON with keys: bullets, assumptions, missing_info_questions",
        agent=bullet_writer,
    )

    critique_task = Task(
        description=f"""
Here is the full resume text:
{resume_text}

Using the Bullet Writer's output as context, evaluate the resume and provide:
1. 3-5 specific improvement suggestions
2. Weak or vague bullet points, if any
3. Suggestions for tailoring to roles like: data analyst, product manager, ML engineer

Return your response in a clear, structured format.
""".strip(),
        expected_output="Structured feedback with improvement suggestions, weak bullets, role-tailoring advice",
        agent=resume_critic,
        context=[bullet_task],
    )

    # --- Run Crew ---
    crew = Crew(tasks=[bullet_task, critique_task], claude_model=claude_model)
    outputs = crew.kickoff()

    # --- Parse bullet output ---
    bullet_raw = outputs[0] if outputs else ""
    try:
        payload = safe_load_json(bullet_raw)
        bullets, assumptions, missing = validate_bullets_payload(
            payload, min_bullets=MIN_BULLETS, max_bullets=MAX_BULLETS
        )
        bullets = normalize_bullets(bullets, max_chars=MAX_BULLET_CHARS, max_bullets=MAX_BULLETS)
    except SchemaError:
        fallback = normalize_bullets(
            [ln.strip("• ").strip() for ln in bullet_raw.splitlines() if ln.strip()],
            max_chars=MAX_BULLET_CHARS
        )
        fallback = fallback[:MAX_BULLETS]
        if len(fallback) < MIN_BULLETS:
            fallback = [
                "Built an end-to-end resume editing workflow emphasizing reliability and structured LLM output.",
                "Implemented multi-agent pipeline with schema validation to reduce hallucinations and formatting errors.",
            ][:MAX_BULLETS]
        bullets, assumptions, missing = fallback, [], []

    feedback = outputs[1] if len(outputs) > 1 else ""

    return bullets, assumptions, missing, feedback

